name: Citrea Frontend DEV CI/CD

on:
  push:
    branches: [develop]
  workflow_dispatch:

env:
  DOCKER_TAGS: dfxswiss/citrea-frontend:beta
  AZURE_RESOURCE_GROUP: rg-dfx-api-dev
  AZURE_VM_NAME: vm-dfx-node-dev
  AZURE_FRONT_DOOR: 'afd-dfx-api-dev'
  AZURE_FRONT_DOOR_ENDPOINT: 'fde-dfx-ctef-dev'

jobs:
  build-and-deploy:
    name: Build, test and deploy to DEV
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_TAGS }}

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.DFX_DEV_CREDENTIALS }}
        
      - name: Update Azure VM docker container
        uses: azure/CLI@v2
        with:
          inlineScript: |
            echo "Update docker container..."

            CONTENT_DEV=$(base64 -w0 ./.env.dev)
            CONTENT_PRD=$(base64 -w0 ./.env.prd)

            az vm run-command invoke \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --name ${{ env.AZURE_VM_NAME }} \
              --command-id RunShellScript \
              --scripts "
                echo $CONTENT_DEV | base64 -d > /home/dfx/docker-compose-blockscout-citrea-testnet.frontend.env &&
                echo $CONTENT_PRD | base64 -d > /home/dfx/docker-compose-blockscout-citrea-mainnet.frontend.env &&
                /home/dfx/update-blockscout.sh frontend
              "

      - name: Purge Frontdoor endpoint
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az afd endpoint purge \
              --content-paths "/*" \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --profile-name ${{ env.AZURE_FRONT_DOOR }} \
              --endpoint-name ${{ env.AZURE_FRONT_DOOR_ENDPOINT }} \
              --no-wait

      - name: Logout from Azure
        run: |
          az logout
        if: always()
